import type { Citation } from "@/lib/ai/types";

/**
 * Report → printable HTML. We generate a fully-styled, self-contained HTML
 * document and let the browser's native print-to-PDF produce the file. This
 * keeps the MVP dependency-free (no Puppeteer/Chromium download) and reliable
 * across platforms. The HTML is also the preview shown in the app.
 *
 * A server-side PDF binary path (Playwright/react-pdf) can be swapped in later
 * behind this same interface without touching callers.
 */

export interface ReportInput {
  title: string;
  contentMd: string;
  citations?: Citation[];
  author?: string;
  generatedAt?: Date;
}

export function renderReportHtml(input: ReportInput): string {
  const { title, contentMd, citations = [], author, generatedAt = new Date() } = input;
  const bodyHtml = mdToHtml(contentMd);
  const citationsHtml = citations.length
    ? `<section class="citations"><h2>Sources</h2><ol>${citations
        .map((c) => `<li>${citationLine(c)}</li>`)
        .join("")}</ol></section>`
    : "";

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>${escapeHtml(title)}</title>
<style>
  :root { --ink:#1a1d24; --muted:#606770; --accent:#4f46e5; --line:#e5e7eb; }
  * { box-sizing: border-box; }
  body {
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Inter, Roboto, sans-serif;
    color: var(--ink); line-height: 1.6; margin: 0;
    padding: 48px; max-width: 820px; margin-inline: auto; font-size: 15px;
  }
  header.doc { border-bottom: 3px solid var(--accent); padding-bottom: 16px; margin-bottom: 28px; }
  header.doc h1 { font-size: 30px; margin: 0 0 6px; letter-spacing: -0.02em; }
  header.doc .meta { color: var(--muted); font-size: 13px; }
  h1,h2,h3 { line-height: 1.25; letter-spacing: -0.01em; }
  h2 { font-size: 21px; margin-top: 30px; border-bottom: 1px solid var(--line); padding-bottom: 6px; }
  h3 { font-size: 17px; margin-top: 22px; }
  p { margin: 12px 0; }
  ul, ol { margin: 12px 0; padding-left: 24px; }
  li { margin: 4px 0; }
  a { color: var(--accent); }
  code { background: #f3f4f6; padding: 2px 5px; border-radius: 4px; font-size: 0.9em; }
  pre { background: #0d1117; color: #e6edf3; padding: 16px; border-radius: 8px; overflow-x: auto; }
  pre code { background: transparent; color: inherit; padding: 0; }
  blockquote { border-left: 3px solid var(--line); margin: 12px 0; padding-left: 16px; color: var(--muted); }
  table { border-collapse: collapse; width: 100%; margin: 16px 0; font-size: 14px; }
  th, td { border: 1px solid var(--line); padding: 8px 10px; text-align: left; }
  th { background: #f9fafb; }
  .citations { margin-top: 40px; border-top: 1px solid var(--line); padding-top: 16px; }
  .citations h2 { border: 0; }
  .citations li { font-size: 13px; color: var(--muted); }
  @media print { body { padding: 0; } @page { margin: 2cm; } }
</style>
</head>
<body>
  <header class="doc">
    <h1>${escapeHtml(title)}</h1>
    <div class="meta">Generated by Aria${author ? " · " + escapeHtml(author) : ""} · ${generatedAt.toLocaleDateString()}</div>
  </header>
  <main>${bodyHtml}</main>
  ${citationsHtml}
</body>
</html>`;
}

function citationLine(c: Citation): string {
  if (c.url) {
    return `<a href="${escapeHtml(c.url)}">${escapeHtml(c.title || c.url)}</a>`;
  }
  const loc = c.page ? ` (p.${c.page})` : "";
  return `${escapeHtml(c.title)}${loc}`;
}

/**
 * Minimal, safe Markdown → HTML. Handles headings, lists, tables, code, bold,
 * italic, links, blockquotes. Escapes HTML first to prevent injection.
 */
export function mdToHtml(md: string): string {
  const escaped = escapeHtml(md);
  const lines = escaped.split("\n");
  const out: string[] = [];
  let inCode = false;
  let inList: "ul" | "ol" | null = null;
  let tableBuffer: string[] = [];

  const closeList = () => {
    if (inList) {
      out.push(`</${inList}>`);
      inList = null;
    }
  };
  const flushTable = () => {
    if (tableBuffer.length >= 2) out.push(renderTable(tableBuffer));
    else out.push(...tableBuffer.map((l) => `<p>${inline(l)}</p>`));
    tableBuffer = [];
  };

  for (const raw of lines) {
    const line = raw;

    if (line.trim().startsWith("```")) {
      flushTable();
      closeList();
      if (!inCode) {
        out.push("<pre><code>");
        inCode = true;
      } else {
        out.push("</code></pre>");
        inCode = false;
      }
      continue;
    }
    if (inCode) {
      out.push(line + "\n");
      continue;
    }

    // Tables (lines containing a pipe, gathered until a blank line).
    if (/\|/.test(line) && line.trim().length > 0) {
      tableBuffer.push(line);
      continue;
    } else if (tableBuffer.length) {
      flushTable();
    }

    const h = line.match(/^(#{1,6})\s+(.*)$/);
    if (h) {
      closeList();
      const level = Math.min(h[1].length, 6);
      out.push(`<h${level}>${inline(h[2])}</h${level}>`);
      continue;
    }

    if (/^\s*>\s?/.test(line)) {
      closeList();
      out.push(`<blockquote>${inline(line.replace(/^\s*>\s?/, ""))}</blockquote>`);
      continue;
    }

    const ol = line.match(/^\s*\d+\.\s+(.*)$/);
    const ul = line.match(/^\s*[-*]\s+(.*)$/);
    if (ol) {
      if (inList !== "ol") {
        closeList();
        out.push("<ol>");
        inList = "ol";
      }
      out.push(`<li>${inline(ol[1])}</li>`);
      continue;
    }
    if (ul) {
      if (inList !== "ul") {
        closeList();
        out.push("<ul>");
        inList = "ul";
      }
      out.push(`<li>${inline(ul[1])}</li>`);
      continue;
    }

    closeList();
    if (line.trim() === "") continue;
    out.push(`<p>${inline(line)}</p>`);
  }
  flushTable();
  closeList();
  if (inCode) out.push("</code></pre>");
  return out.join("\n");
}

function renderTable(rows: string[]): string {
  const cells = (r: string) =>
    r
      .trim()
      .replace(/^\||\|$/g, "")
      .split("|")
      .map((c) => c.trim());
  const header = cells(rows[0]);
  const bodyRows = rows.slice(2); // rows[1] is the --- separator
  const thead = `<thead><tr>${header.map((c) => `<th>${inline(c)}</th>`).join("")}</tr></thead>`;
  const tbody = `<tbody>${bodyRows
    .map((r) => `<tr>${cells(r).map((c) => `<td>${inline(c)}</td>`).join("")}</tr>`)
    .join("")}</tbody>`;
  return `<table>${thead}${tbody}</table>`;
}

function inline(text: string): string {
  return text
    .replace(/`([^`]+)`/g, "<code>$1</code>")
    .replace(/\*\*([^*]+)\*\*/g, "<strong>$1</strong>")
    .replace(/\*([^*]+)\*/g, "<em>$1</em>")
    .replace(/\[([^\]]+)\]\(([^)]+)\)/g, '<a href="$2">$1</a>');
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}
